name: IOSRunnerPlayground

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"

targets:
  IOSRunnerPlayground:
    type: application
    platform: iOS

    sources:
      - path: App

    resources:
      - path: App/Data/lpyAccounts.db

    info:
      properties:
        NSAppTransportSecurity:
          NSExceptionDomains:
            www.leafmines.co.uk:
              NSExceptionAllowsInsecureHTTPLoads: true

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.IOSRunnerPlayground
        PRODUCT_NAME: IOSRunnerPlayground
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"

  IOSRunnerPlaygroundUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: IOSRunnerPlayground
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.IOSRunnerPlaygroundUITests
        SWIFT_VERSION: "5.0"
```